# don't change this
configversion: 4
#DataBase
DataBase:
  # You need to choose if you will use SQLite or Mysql ( default is SQLite )
  Type: SQLite
#MySQL config if you will use mysql ( set type to mysql )
MySQL:
  Host: localhost
  Username: root
  Password: change_this
  Port: '3306'
  Database: minecraft
# Enable update
UpdaterNotify: true
# How Many Life For Each Core
CoreLife: 20
# Don't drop item on kill during event
Dontdropduringevent: true
# Defaults flags set to area
DefaultFlags:
    ClanOwnerCanBreakArea: false
    ClanOwnerCanPlaceArea: false