# don't change this
configversion: 6
#DataBase
DataBase:
  # You need to choose if you will use SQLite or Mysql ( default is SQLite )
  Type: SQLite
#MySQL config if you will use mysql ( set type to mysql )
MySQL:
  Host: localhost
  Username: root
  Password: change_this
  Port: '3306'
  Database: minecraft
# Enable update
UpdaterNotify: true
# How Many Life For Each Core
CoreLife: 20
# What id of block 
CoreBlockId: 49
# Don't drop item on kill during event
# The item will auto-save and 
# add back after player re-spawn
# if player inv is full the item will
# be lost forever
Dontdropduringevent: true
# Don't die during event
# will don't let player die
# anytime player will die 
# he will be teleport to exit
# point and get full health again
Dontdieduringevent: false
# Defaults flags set to area
DefaultFlags:
    ClanOwnerCanBreakArea: false
    ClanOwnerCanPlaceArea: false